CREATE TABLE stock (
                       id BIGSERIAL PRIMARY KEY,
                       symbol VARCHAR(10) NOT NULL UNIQUE,
                       name VARCHAR(120),
                       active BOOLEAN DEFAULT TRUE,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO stock (symbol, name) VALUES
                                     ('PETR4', 'Petrobras PN'),
                                     ('PETR3', 'Petrobras ON'),
                                     ('VALE3', 'Vale ON'),
                                     ('ITUB4', 'Itaú Unibanco PN'),
                                     ('ITSA4', 'Itaúsa PN'),
                                     ('BBDC4', 'Bradesco PN'),
                                     ('BBDC3', 'Bradesco ON'),
                                     ('BBAS3', 'Banco do Brasil ON'),
                                     ('ABEV3', 'Ambev ON'),
                                     ('WEGE3', 'WEG ON'),
                                     ('SUZB3', 'Suzano ON'),
                                     ('JBSS3', 'JBS ON'),
                                     ('PRIO3', 'PetroRio ON'),
                                     ('GGBR4', 'Gerdau PN'),
                                     ('CSNA3', 'CSN ON'),
                                     ('USIM5', 'Usiminas PN'),
                                     ('RAIL3', 'Rumo ON'),
                                     ('VIVT3', 'Telefônica Brasil ON'),
                                     ('TIMS3', 'TIM ON'),
                                     ('CIEL3', 'Cielo ON'),
                                     ('LREN3', 'Lojas Renner ON'),
                                     ('MGLU3', 'Magazine Luiza ON'),
                                     ('AMER3', 'Americanas ON'),
                                     ('B3SA3', 'B3 ON'),
                                     ('EQTL3', 'Equatorial Energia ON'),
                                     ('CPLE6', 'Copel PN'),
                                     ('CMIG4', 'Cemig PN'),
                                     ('ELET3', 'Eletrobras ON'),
                                     ('ELET6', 'Eletrobras PN'),
                                     ('ENGI11', 'Energisa Units'),
                                     ('TAEE11', 'Taesa Units'),
                                     ('KLBN11', 'Klabin Units'),
                                     ('BRFS3', 'BRF ON'),
                                     ('MRFG3', 'Marfrig ON'),
                                     ('HAPV3', 'Hapvida ON'),
                                     ('RADL3', 'Raia Drogasil ON'),
                                     ('FLRY3', 'Fleury ON'),
                                     ('QUAL3', 'Qualicorp ON'),
                                     ('YDUQ3', 'Yduqs ON'),
                                     ('COGN3', 'Cogna ON'),
                                     ('EZTC3', 'EZTEC ON'),
                                     ('CYRE3', 'Cyrela ON'),
                                     ('MRVE3', 'MRV ON'),
                                     ('MULT3', 'Multiplan ON'),
                                     ('IGTI11', 'Iguatemi Units'),
                                     ('BRAP4', 'Bradespar PN'),
                                     ('SANB11', 'Santander Units'),
                                     ('RENT3', 'Localiza ON'),
                                     ('LCAM3', 'Locamerica ON'),
                                     ('AZUL4', 'Azul PN'),
                                     ('GOLL4', 'Gol PN'),
                                     ('CCRO3', 'CCR ON'),
                                     ('ECOR3', 'EcoRodovias ON'),
                                     ('SBSP3', 'Sabesp ON'),
                                     ('CSMG3', 'Copasa ON'),
                                     ('ASAI3', 'Assaí ON'),
                                     ('CRFB3', 'Carrefour Brasil ON'),
                                     ('PCAR3', 'Pão de Açúcar ON'),
                                     ('NTCO3', 'Natura ON'),
                                     ('LWSA3', 'Locaweb ON'),
                                     ('TOTS3', 'Totvs ON'),
                                     ('POSI3', 'Positivo ON'),
                                     ('ALPA4', 'Alpargatas PN'),
                                     ('HYPE3', 'Hypera ON'),
                                     ('PSSA3', 'Porto Seguro ON'),
                                     ('BBSE3', 'BB Seguridade ON'),
                                     ('IRBR3', 'IRB Brasil RE ON'),
                                     ('CVCB3', 'CVC ON'),
                                     ('SMTO3', 'São Martinho ON');
